{% set name = "hwm" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hwm-{{ version }}.tar.gz
  sha256: 65d481821c653baff10c617a5acc0e24c9b30ef1e4a61d211b65078725d98856

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy <2
    - scipy >=1.7.0
    - scikit-learn >=1.2.0
    - pandas >=1.3.0
    - matplotlib-base >=3.5.2  
    
test:
  imports:
    - hwm
    - hwm.api
    - hwm.compat
    - hwm.datasets
    - hwm.estimators
    - hwm.utils
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/earthai-tech/hwm
  summary: Adaptive Hammerstein-Wiener Modeling Toolkit
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    HWM is a Python toolkit for adaptive dynamic system
    modeling, designed to capture complex nonlinear and
    linear relationships in data through the Hammerstein-Wiener architecture.
    With a flexible, modular design, HWM integrates seamlessly with
    Scikit-learn, enabling streamlined workflows for regression,
    classification, and time-series forecasting tasks. 
  doc_url: "https://hwm.readthedocs.io"
  dev_url: "https://github.com/earthai-tech/hwm"

extra:
  recipe-maintainers:
    - earthai-tech
